language: node_js
sudo: false
node_js:
- node
- '5'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
notifications:
  slack:
    rooms:
      - prprteam:VrTwaK9Iks4sbPMlrfXZdDDQ
    on_success: never
before_install:
- openssl aes-256-cbc -K $encrypted_753eb4a09846_key -iv $encrypted_753eb4a09846_iv
  -in secret.js.enc -out server/config/secret.js -d
